### ISSUE TITLE
{"status":"ERROR","message":"Unknown reserved word: {localeCode}"}

### ISSUE THREAD

**Issue by pdurbin** [scholarsportal/Dataverse-Data-Explorer#14]
I'm on dfd6a2f (master branch) and just downloaded dataExplorer.json from the README. When I run `curl -X POST -H 'Content-type: application/json' --upload-file dataExplorer.json http://localhost:8080/api/admin/externalTools`, I get this error:

```
{
  "status": "ERROR",
  "message": "Unknown reserved word: {localeCode}"
}
```

I talked a bit with @manikon about this at https://github.com/IQSS/dataverse/issues/5456#issuecomment-463299666

**Comment by pdurbin** [comment]
I just bumped into this again. I'd be happy to make a pull request if that helps.

Also, my understanding is that localeCode will be added as part of https://github.com/IQSS/dataverse/issues/6215

**Comment by kaitlinnewson** [comment]
@lubitchv should `"dvLocale": "{localeCode}"` be removed from the config for versions before 4.17 as well?

**Comment by lubitchv** [comment]
@kaitlinnewson Probably. SP installation had dvLocale  for Data Explore before 4.17 version, but it was not in IQSS code. That is why it is still there. I will remove it, thanks for noticing.

**Comment by lubitchv** [comment]
@kaitlinnewson I just removed dvLocale for old versions.
