### ISSUE TITLE
Document need to enable CORS on Dataverse installation

### ISSUE THREAD

**Issue by pdurbin** [scholarsportal/Dataverse-Data-Explorer#2]
I was just scratching my head about why https://scholarsportal.github.io/Dataverse-Data-Explorer/?siteUrl=https://dataverse.harvard.edu&fileId=3040230 is working fine but https://scholarsportal.github.io/Dataverse-Data-Explorer/?siteUrl=https://dev1.dataverse.org&fileid=15 isn't. I looked at the Javascript error console and saw this:

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://dev1.dataverse.org/api/access/datafile//metadata/ddi. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).`

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://dev1.dataverse.org/api/access/datafile/?format=prep&key=null. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).`

Here's a screenshot of the errors and the blank page with a blue progress bar on the top:

<img width="686" alt="screen shot 2018-01-05 at 1 19 47 pm" src="https://user-images.githubusercontent.com/21006/34622533-8f585120-f21b-11e7-8d59-be5aec2fa398.png">

I'm pretty sure I know how to fix this but in the documentation for Data Explorer you should probably mention the need to enable CORS on your installation of Dataverse for the tool to work.

**Comment by pdurbin** [comment]
Huh, I thought adding `Header set Access-Control-Allow-Origin "*"` to Apache like below would help (I front Glassfish with Apache) but I still can't get Data Explorer working:

```
[root@dvnweb-vm2 ~]# cd /etc/httpd/conf.d
[root@dvnweb-vm2 conf.d]# cp -a ssl.conf ssl.conf.`date -I`
[root@dvnweb-vm2 conf.d]# vim ssl.conf
[root@dvnweb-vm2 conf.d]# /etc/init.d/httpd restart
Stopping httpd:                                            [  OK  ]
Starting httpd:                                            [  OK  ]
[root@dvnweb-vm2 conf.d]# diff -u ssl.conf.2018-01-05 ssl.conf
--- ssl.conf.2018-01-05	2017-06-30 21:20:50.136849474 -0400
+++ ssl.conf	2018-01-05 15:36:01.411992823 -0500
@@ -228,6 +228,7 @@
 ProxyPassMatch ^/open-source-at-harvard !
 
 ProxyPass / ajp://localhost:8009/
+Header set Access-Control-Allow-Origin "*"
 
 </VirtualHost>                                  
 
[root@dvnweb-vm2 conf.d]# 
```

Any ideas for me?

**Comment by kevinworthington** [comment]
Hi @pdurbin,
I'm sorry to hear you're having issues with CORS but the API's are open to the word so that can't be the issue. Looking at your call I can see that the error is related to a lowercase "I" in "fileid"
 https://scholarsportal.github.io/Dataverse-Data-Explorer/?fileId=15&siteUrl=https://dev1.dataverse.org

**Comment by pdurbin** [comment]
@kevinworthington whoops! Fixed in https://github.com/IQSS/dataverse/commit/e873c6e5e5aa5f2d981834d1780dbfff5948c774 . Thanks!

**Comment by pdurbin** [comment]
I backed out the `Header set Access-Control-Allow-Origin "*"` above and it still works with just the fix to the case of `fileId`. Sorry for the noise. Closing.

**Comment by pdurbin** [comment]
> https://dev1.dataverse.org/api/access/datafile//metadata/ddi

By the way, this URL with the double slash and no file id should have been my clue that something was up with how the file id was being passed. 😄
