### ISSUE TITLE
add preview mode support

### ISSUE THREAD

**Issue by pdurbin** [scholarsportal/Dataverse-Data-Explorer#21]
Hi! Over in https://github.com/QualitativeDataRepository/dataverse-previewers/pull/27 we added "preview mode" support to QDR's File Previewers. It looks something like this:

![Screen Shot 2019-11-12 at 11 57 50 AM](https://user-images.githubusercontent.com/21006/68692552-ace72a80-0543-11ea-9015-0678f3ab0d4e.png)

It's possible to add Data Explorer to the new "Preview" tab and here's how it look right now:

![Screen Shot 2019-11-12 at 11 58 12 AM](https://user-images.githubusercontent.com/21006/68692600-c4beae80-0543-11ea-8273-52238363de5d.png)

I'm opening this issue to start a conversation about what a "preview mode" for Data Explorer could look like. The main thing we did with QDR's File Previewers is hide the header, the part of the page in the red box below...

![67304462-d9b69d80-f4c1-11e9-94ac-83221ef8af62](https://user-images.githubusercontent.com/21006/68692785-0f402b00-0544-11ea-8ea3-abc43145bbfe.png)

... but you could, of course, do whatever you want with "preview mode" for Data Explorer.

What do you think? 😄

**Comment by kaitlinnewson** [comment]
Closing this as we're not updating this version of the Data Explorer, and moving over to: https://github.com/scholarsportal/dataverse-data-explorer-v2/issues/7
