### ISSUE TITLE
contentType is required when uploading json file via API

### ISSUE THREAD

**Issue by thu07** [scholarsportal/Dataverse-Data-Explorer#22]
I try to add external tools in my Dataverse instance when uploading the dataExplorer.json file following the instruction. However, it failed as shown below.

Dataverse version: 4.19

![111111](https://user-images.githubusercontent.com/40651520/74466651-a9767e80-4e65-11ea-98c3-58b8d58b1da2.png)

**Comment by kaitlinnewson** [comment]
Based on what's in http://guides.dataverse.org/en/latest/admin/external-tools.html, I think we just need to add something like:

`"contentType": "text/tab-separated-values",`

... to the default dataExplorer.json file. Does this sound correct @lubitchv or @manikon?

**Comment by lubitchv** [comment]
@kaitlinnewson Yes, you are right. contentType and scope were added in version 17 and up. I did update Data Curation Tool, but not Data Explorer. I will update it tomorrow, will create a manifest json for v17 and up.

**Comment by lubitchv** [comment]
@kaitlinnewson I added ccontentType and scope to dataExplorer_v4.17up.json and dataExplorerLocal_v4.17up.json and changed installation instructions accordingly.
