### ISSUE TITLE
Data-Explorer in DataverseEU-Docker

### ISSUE THREAD

**Issue by mshariful** [scholarsportal/Dataverse-Data-Explorer#23]
Hi all,
I have successfully installed DataverseEU-Docker version in Ubuntu. After downloading 
dataExplorer.json  in a local folder, I cd to that folder and  tried to execute the command

curl -X POST -H 'Content-type: application/json' --upload-file dataExplorer.json http://localhost:8080/api/admin/externalTools

I got the following errors:

{ status:"error", message:"Endpoint available from localhost only. Please contact the dataverse administrator"}

Could you please help. Thank you very much.

Kind regards,
Sharif

**Comment by kaitlinnewson** [comment]
@mshariful have you ssh'ed into the docker container before running the command? e.g. see this related issue: https://github.com/IQSS/dataverse-docker/issues/17

You also previously submitted #20 which was the same problem. Have you also tried what was recommended here?  https://github.com/IQSS/dataverse-docker/issues/29

This issue appears to be related to https://github.com/IQSS/dataverse-docker and not the data explorer itself, so I'm going to close this, but feel free to re-open if you see an issue with the data explorer tool itself.
