### ISSUE TITLE
Table View not updating when variable selected

### ISSUE THREAD

**Issue by kevinworthington** [scholarsportal/Dataverse-Data-Explorer#24]
When a variable is selected and the interface is set to Table View, the build table event doesn't get called. If however, the Chart View tab is selected and then the user switches to Table View, the table is built as expected.

**Comment by kaitlinnewson** [comment]
Hey @kevinworthington, thanks for the issue report! We're not updating this version of the Data Explorer anymore and have a new version, but please let us know if you find similar issues in the new version: https://github.com/scholarsportal/dataverse-data-explorer-v2/
