### ISSUE TITLE
As a sysadmin configuring Dataverse, I want to enable Data Explorer using the hosted version on GitHub

### ISSUE THREAD

**Issue by pdurbin** [scholarsportal/Dataverse-Data-Explorer#3]
Right now the installation instructions say "Instructions for easy implementation as part of your Dataverse instance are coming soon." This is expected because https://github.com/IQSS/dataverse/issues/3657 is still in flux and its corresponding pull request has not been merged.

As I see it there are two ways to configure Dataverse to use Data Explorer:

- Configure Dataverse to use the version of Data Explorer hosted on GitHub at https://scholarsportal.github.io/Dataverse-Data-Explorer/
- Install Data Explorer on your own server and configure Dataverse to use that server

Does that sound right? Part of why I'm opening this issue is that I pushed an "external tool manifest" file called "dataExplorer.json" into the Dataverse code base but I want this JSON file to be maintained and hosted by Data Explorer developers rather than Dataverse developers. Perhaps it could be added to this "Dataverse-Data-Explorer" git repo. Basically, the Dataverse team wants each "external tool" to be responsible for explaining how to install and configure the tool. That's what https://github.com/IQSS/dataverse/issues/4429 is about. In the Dataverse Guides, we are happy to provide a paragraph blurb about each tool and link to the installation instructions that are hosted and maintained by the tool author.

I tried to keep this scope of this issue small by only being about the option of using the GitHub-hosted version (something I think I could make a pull request for) but if it would be better for the scope to be increased to be full installation instructions on your own server that's fine (but I won't be able to help).

**Comment by kevinworthington** [comment]
The installations instructions have been updated.
