### ISSUE TITLE
Dataset can't save if text is copied from PDF.

### ISSUE THREAD

**Issue by nana-boateng** [scholarsportal/Dataverse-Data-Explorer#54]
If the copied text includes a line break, something about that prevents it from saving.

**Comment by whitebroghan** [comment]
When copying variable metadata from a pdf and pasting into a text box in the Data Curation Tool, text that contains special formatting such as line breaks prevent you from being able to save the metadata.

To get around this, you have to find the spot where the formatting occurs (at the line break) and delete it.

https://github.com/scholarsportal/Dataverse-Data-Curation-Tool/assets/148995196/ed0680ff-7d09-44f1-ab8a-bb16d10585bf

**Comment by nana-boateng** [comment]
Fixed in https://github.com/scholarsportal/Dataverse-Data-Curation-Tool/pull/72
