### ISSUE TITLE
Redesign for drop-down download menu?

### ISSUE THREAD

**Issue by mhvezina** [scholarsportal/Dataverse-Data-Explorer#8]
May I suggest a redesign for this menu? 

![original](https://user-images.githubusercontent.com/10760472/37367702-0dc981fe-26fc-11e8-8c61-e972e6d26aaa.png)

Could be something like:

1) 
Download...
  ... a subset
  ... the original file format
  ... a tab-delimited file
  ... a RDA format file
  ... the variable metadata

or

2) 
Download : [---SELECT one : ---]       <="Download" is a snippet of text in front of the select box
         subset
         original file
        tab-delimited file
        (...)

What do you think?

**Comment by kevinworthington** [comment]
Hi @mhvezina,
Thanks for your suggestions. I like option 2 :) I'll be sure to update it shortly.

**Comment by kevinworthington** [comment]
Hi @mhvezina,
The download dropdown wording has been updated as suggested.

Kevin
